#!/bin/bash

######################################################################################
# parse-args - Run an evaluation on all the arguments to an app. Sets ENV variables for 
#  named data. Puts positional args in `args` array. Sets small flags to a value of '1'
# 
# USAGE:
#    source parse-args
######################################################################################

positional_args=()
args=()
until [ -z "$1" ]; do
  if [[ "$1" == "-"* ]]; then
    key=`echo "$1" | sed -e "s/-/_/g"`
    eval "$key=1"
    eval "${key}_VALUE='$2'"
  else
    positional_args+=("$1")
  fi
  args+=("$1");
  shift 1;
done
