name: CI Test

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-latest
    
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install and Test
      run: |
        npm install;
        source ~/.bashful.filesys/bashful.rc;
        npm test;
