name: CI Test

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and Test
      run: |
        npm install;
        source ~/.bashful.filesys/bashful.rc;
        npm test;
